/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#fcfcff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#c1c7cf",
        "surface-container": "#eceef1",
        "outline-variant": "#bec8ce",
        "on-background": "#191c1e",
        "outline": "#6e797e",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#74d2f9",
        "surface-variant": "#e0e3e6",
        "secondary-fixed-dim": "#bcc7dd",
        "background": "#f7f9fc",
        "tertiary-fixed": "#dde3eb",
        "surface": "#f7f9fc",
        "surface-container-high": "#e6e8eb",
        "secondary-container": "#d5e0f7",
        "on-secondary-fixed-variant": "#3c475a",
        "primary-container": "#007ea1",
        "surface-dim": "#d8dadd",
        "on-secondary-container": "#586377",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#fbfdff",
        "on-secondary-fixed": "#111c2c",
        "on-primary-fixed": "#001f2a",
        "surface-tint": "#006783",
        "inverse-on-surface": "#eff1f4",
        "surface-container-low": "#f2f4f7",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#bce9ff",
        "tertiary-container": "#6f757c",
        "secondary": "#545f72",
        "on-tertiary-fixed-variant": "#41474e",
        "surface-bright": "#f7f9fc",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#004d64",
        "tertiary": "#565d63",
        "inverse-primary": "#74d2f9",
        "on-surface-variant": "#3e484d",
        "secondary-fixed": "#d8e3fa",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e6",
        "on-tertiary-fixed": "#161c22",
        "primary": "#006480",
        "on-error-container": "#93000a",
        "myan-primary": "#0084A8"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "container-padding": "24px",
        "card-gap": "20px",
        "gutter": "16px"
      },
      fontFamily: {
        "display-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["13px", {"lineHeight": "18px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
